# Generated by Django 4.2.5 on 2023-11-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.usuario')),
                ('venta_id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.venta')),
            ],
        ),
    ]
