# Generated by Django 4.2.5 on 2023-11-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_id_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nerdapp.categoria'),
            preserve_default=False,
        ),
    ]
