# Generated by Django 4.2.5 on 2023-10-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0002_participarsubasta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participarsubasta',
            old_name='id_subasta',
            new_name='subasta_id_subasta',
        ),
        migrations.RenameField(
            model_name='participarsubasta',
            old_name='id_usuario',
            new_name='usuario_id_usuario',
        ),
    ]
