# Generated by Django 4.2.5 on 2023-10-01 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0002_remove_categoria_id_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria_id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.categoria')),
                ('inventario_id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.inventario')),
            ],
        ),
    ]
