# Generated by Django 4.2.5 on 2023-10-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0003_rename_id_subasta_participarsubasta_subasta_id_subasta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participarsubasta',
            old_name='subasta_id_subasta',
            new_name='subasta_id_subasta_id',
        ),
        migrations.RenameField(
            model_name='participarsubasta',
            old_name='usuario_id_usuario',
            new_name='usuario_id_usuario_id',
        ),
    ]
