# Generated by Django 4.2.5 on 2023-10-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0003_inventario_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(default=100, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(default=100, primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id_subasta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_inicial', models.IntegerField()),
                ('precio_mas_alto', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('apellido_paterno', models.CharField(max_length=200, null=True)),
                ('apellido_materno', models.CharField(max_length=200, null=True)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_inventario',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Usuario_subasta',
            fields=[
                ('id_usuario_subasta', models.IntegerField(primary_key=True, serialize=False)),
                ('subasta_id_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.subasta')),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_publicacion', models.CharField(max_length=200)),
                ('descripcion_publicacion', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('estado_publicacion', models.CharField(max_length=200)),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.IntegerField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=200)),
                ('producto_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.producto')),
                ('subasta_id_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.subasta')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(default=100, primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=200)),
                ('region_id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.IntegerField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=200)),
                ('fecha_comentario', models.DateField()),
                ('estado_comentario', models.CharField(max_length=200)),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('total_venta', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerdapp.usuario')),
            ],
        ),
    ]
