# Generated by Django 4.2.5 on 2023-11-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0004_venta_usuario_id_usuario2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='usuario_id_usuario2',
        ),
    ]
