# Generated by Django 4.2.5 on 2023-11-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0004_rename_subasta_id_subasta_participarsubasta_subasta_id_subasta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='publicacion_id_publicacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nerdapp.publicacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion_publicacion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
