# Generated by Django 4.2.5 on 2023-10-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='hora_inicio',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
