# Generated by Django 4.2.5 on 2023-12-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0005_remove_venta_usuario_id_usuario2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='region_id_region',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
