# Generated by Django 4.2.5 on 2023-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0007_remove_producto_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
