# Generated by Django 4.2.5 on 2023-10-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0008_producto_cantidad_disponible_producto_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
