# Generated by Django 4.2.5 on 2023-10-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0006_alter_foto_foto_alter_subasta_fecha_inicio_and_more'),
        ('nerdapp', '0009_delete_inventario'),
    ]

    operations = [
    ]
