# Generated by Django 4.2.5 on 2023-10-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0010_merge_20231025_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
