# Generated by Django 4.2.5 on 2023-10-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0011_subasta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='subastas'),
        ),
    ]
