# Generated by Django 4.2.5 on 2023-10-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0012_alter_subasta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='id_subasta',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
