# Generated by Django 4.2.5 on 2023-10-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0013_alter_subasta_id_subasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='precio_mas_alto',
            field=models.IntegerField(default=1),
        ),
    ]
