# Generated by Django 4.2.5 on 2023-10-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0014_alter_subasta_precio_mas_alto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='id_subasta',
        ),
        migrations.AddField(
            model_name='subasta',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
