# Generated by Django 4.2.5 on 2023-10-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0017_remove_subasta_id_subasta_subasta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='precio_mas_alto',
            field=models.IntegerField(default=10),
        ),
    ]
