# Generated by Django 4.2.5 on 2023-10-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0018_alter_subasta_precio_mas_alto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='id',
        ),
        migrations.AddField(
            model_name='subasta',
            name='id_subasta',
            field=models.IntegerField(default=11, primary_key=True, serialize=False),
        ),
    ]
