# Generated by Django 4.2.5 on 2023-10-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0020_alter_subasta_id_subasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='id_subasta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
