# Generated by Django 4.2.5 on 2023-10-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerdapp', '0023_remove_subasta_id_subasta_subasta_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='id',
        ),
        migrations.AddField(
            model_name='subasta',
            name='id_subasta',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
